# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Code+183296
    ports:
      - 3308:3306

  db1:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Code+183296
      MYSQL_DATABASE: testdb1
    ports:
      - 3307:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080